-- ============================================================
--  Konfiguracja bazy Supabase dla portfolio + finansów
--  Uruchom całość w panelu Supabase: SQL Editor → New query → Run
-- ============================================================


-- ============================================================
--  1. TABELA: debts  (zadłużenia i stałe opłaty)
-- ============================================================
create table if not exists debts (
  id               bigint generated by default as identity primary key,
  created_at       timestamptz not null default now(),
  user_id          uuid not null references auth.users (id) default auth.uid(),

  -- wspólne
  kind             text   not null default 'debt',        -- 'debt' | 'subscription'
  name             text   not null,
  type             text   not null default 'inne',         -- dług: kredyt/paypo/studia/inne
                                                            -- opłata: komorka/internet/streaming/sub_inne
  notes            text,

  -- zadłużenie
  status           text   not null default 'do_zaplaty',   -- 'do_zaplaty' | 'oplacone'
  remaining_amount numeric not null default 0,
  total_amount     numeric,
  monthly_payment  numeric,                                 -- rata długu LUB kwota stałej opłaty
  due_date         date,
  installments     jsonb,                                   -- [{ amount, due_date, paid }]

  -- stała opłata / subskrypcja
  billing_cycle    text,                                    -- 'monthly' | 'yearly'
  active           boolean default true,
  payment_day      int
);

-- Gdyby tabela już istniała — dołóż brakujące kolumny (bezpieczne, idempotentne)
alter table debts add column if not exists user_id          uuid references auth.users (id) default auth.uid();
alter table debts add column if not exists kind             text   not null default 'debt';
alter table debts add column if not exists name             text;
alter table debts add column if not exists type             text   not null default 'inne';
alter table debts add column if not exists notes            text;
alter table debts add column if not exists status           text   not null default 'do_zaplaty';
alter table debts add column if not exists remaining_amount numeric not null default 0;
alter table debts add column if not exists total_amount     numeric;
alter table debts add column if not exists monthly_payment  numeric;
alter table debts add column if not exists due_date         date;
alter table debts add column if not exists installments     jsonb;
alter table debts add column if not exists billing_cycle    text;
alter table debts add column if not exists active           boolean default true;
alter table debts add column if not exists payment_day      int;


-- ---- RLS: każdy widzi i zmienia tylko swoje pozycje ----
alter table debts enable row level security;

drop policy if exists "Allow anon full access on debts" on debts;  -- usuń starą, niebezpieczną
drop policy if exists "Users manage own debts"          on debts;

create policy "Users manage own debts"
  on debts for all
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);


-- ============================================================
--  2. TABELA: posters  (galeria koncertów)
--     Publiczny odczyt, zapis tylko dla zalogowanych.
-- ============================================================
alter table posters enable row level security;

drop policy if exists "Public read posters" on posters;
create policy "Public read posters"
  on posters for select
  to anon, authenticated
  using (true);

drop policy if exists "Auth write posters" on posters;
create policy "Auth write posters"
  on posters for all
  to authenticated
  using (true)
  with check (true);


-- ============================================================
--  3. UŻYTKOWNIK
--     Konta NIE tworzy się tu — zrób to w panelu:
--     Authentication → Users → Add user  (zaznacz Auto Confirm)
--     Następnie wyłącz publiczne rejestracje:
--     Authentication → Providers → Email → "Enable sign-ups" = OFF
-- ============================================================
